# Generated by Django 5.2.8 on 2025-11-07 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('text1_extra', models.TextField(blank=True, null=True)),
                ('text2_extra', models.TextField(blank=True, null=True)),
                ('text3_extra', models.TextField(blank=True, null=True)),
                ('text4_extra', models.TextField(blank=True, null=True)),
                ('json_text_properties', models.JSONField(blank=True, null=True)),
                ('category', models.JSONField(blank=True, null=True)),
                ('type_of_need', models.JSONField(blank=True, null=True)),
                ('minimum_coverage_amount', models.JSONField(blank=True, null=True)),
                ('maximum_coverage_amount', models.JSONField(blank=True, null=True)),
                ('product_description', models.JSONField(blank=True, null=True)),
                ('benefits', models.JSONField(blank=True, null=True)),
                ('packages', models.JSONField(blank=True, null=True)),
                ('terms_and_conditions', models.FileField(blank=True, null=True, upload_to='terms_and_conditions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_info_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Product_Management.productinfo')),
            ],
        ),
    ]
