# Generated by Django 5.2.8 on 2025-11-10 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNameAndPolicyOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('title', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('first_name', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('middle_name', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('last_name', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('suffix', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('birthdate', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('birthplace', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('civil_status', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('gender', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('nationality', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('telephone_number', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('mobile_number', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('email_address', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('tin_number', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('sss_gsis_number', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('occupation', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('nature_of_business', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('specific_source_of_income', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('permanent_address', models.JSONField(default={'category': '', 'city': '', 'country': 'Philippines', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'state': '', 'street': '', 'value': '', 'zip_code': ''})),
                ('present_address', models.JSONField(default={'category': '', 'city': '', 'country': 'Philippines', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'state': '', 'street': '', 'value': '', 'zip_code': ''})),
                ('office_address', models.JSONField(default={'category': '', 'city': '', 'country': 'Philippines', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'state': '', 'street': '', 'value': '', 'zip_code': ''})),
                ('politically_exposed_person', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('are_you_sure_exposed_person', models.JSONField(default={'category': '', 'field_type': ['text', 'number', 'date', 'email', 'dropdown', 'radio', 'checkbox', 'textarea'], 'key': '', 'name': '', 'required': True, 'value': ''})),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text1_extra', models.JSONField(blank=True, null=True)),
                ('text2_extra', models.JSONField(blank=True, null=True)),
                ('text3_extra', models.JSONField(blank=True, null=True)),
                ('text4_extra', models.JSONField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='product_name_policy_owner_pdfs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
