# Generated by Django 5.2.8 on 2025-11-10 01:45

import Product_Management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0002_productnameandpolicyowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='title',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
    ]
