# Generated by Django 5.2.8 on 2025-11-10 01:50

import Product_Management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0003_alter_productnameandpolicyowner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='are_you_sure_exposed_person',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='birthdate',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='birthplace',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='civil_status',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='email_address',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='first_name',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='gender',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='last_name',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='middle_name',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='mobile_number',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='nationality',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='nature_of_business',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='occupation',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='office_address',
            field=models.JSONField(default=Product_Management.models.default_address),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='permanent_address',
            field=models.JSONField(default=Product_Management.models.default_address),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='politically_exposed_person',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='present_address',
            field=models.JSONField(default=Product_Management.models.default_address),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='specific_source_of_income',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='sss_gsis_number',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='suffix',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='telephone_number',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
        migrations.AlterField(
            model_name='productnameandpolicyowner',
            name='tin_number',
            field=models.JSONField(default=Product_Management.models.default_policy_owner_data),
        ),
    ]
