# Generated by Django 5.2.8 on 2025-11-10 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0004_alter_productnameandpolicyowner_are_you_sure_exposed_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnameandpolicyowner',
            name='pdf_file',
        ),
    ]
