# Generated by Django 5.2.8 on 2025-11-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0005_remove_productnameandpolicyowner_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnameandpolicyowner',
            name='product_name',
        ),
    ]
