# Generated by Django 5.2.8 on 2025-11-10 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0006_remove_productnameandpolicyowner_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productnameandpolicyowner',
            name='product_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product_Management.product'),
            preserve_default=False,
        ),
    ]
