# Generated by Django 5.2.8 on 2025-11-10 03:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0007_productnameandpolicyowner_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductNameAndPolicyOwner',
            new_name='PolicyOwner',
        ),
    ]
