# Generated by Django 5.2.8 on 2025-11-10 05:51

import Product_Management.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0008_rename_productnameandpolicyowner_policyowner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyOwnerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=255, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('tin_number', models.JSONField(default=Product_Management.models.default_policy_owner_data)),
                ('sss_gsis_number', models.JSONField(default=Product_Management.models.default_policy_owner_data)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=255, null=True)),
                ('specific_source_of_income', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address', models.CharField(blank=True, max_length=255, null=True)),
                ('office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('politically_exposed_person', models.CharField(blank=True, max_length=255, null=True)),
                ('are_you_sure_exposed_person', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text1_extra', models.CharField(blank=True, max_length=255, null=True)),
                ('text2_extra', models.CharField(blank=True, max_length=255, null=True)),
                ('text3_extra', models.CharField(blank=True, max_length=255, null=True)),
                ('text4_extra', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='Product_Management.policyowner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
