# Generated by Django 5.2.8 on 2025-11-10 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0009_policyownerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyownerdata',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product_Management.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policyownerdata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
