# Generated by Django 5.2.8 on 2025-11-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0010_policyownerdata_product_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyowner',
            options={'verbose_name': 'Policy Owner', 'verbose_name_plural': 'Policy Owners'},
        ),
        migrations.AlterModelOptions(
            name='policyownerdata',
            options={'verbose_name': 'Policy Owner Data', 'verbose_name_plural': 'Policy Owner Data'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'Product Info', 'verbose_name_plural': 'Product Infos'},
        ),
        migrations.AlterModelOptions(
            name='productinfoimage',
            options={'verbose_name': 'Product Info Image', 'verbose_name_plural': 'Product Info Images'},
        ),
    ]
