# Generated by Django 5.2.8 on 2025-11-10 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0011_alter_policyowner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyownerdata',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product_Management.policyowner'),
        ),
        migrations.AlterField(
            model_name='policyownerdata',
            name='sss_gsis_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyownerdata',
            name='tin_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
