# Generated by Django 5.2.8 on 2025-11-10 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0012_alter_policyownerdata_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyowner',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product_Management.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policyowner',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='policyownerdata',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_owner_data', to='Product_Management.policyowner'),
        ),
    ]
