# Generated by Django 5.2.8 on 2025-11-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0013_policyowner_product_alter_policyowner_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyowner',
            name='product_name',
        ),
    ]
