# Generated by Django 5.2.8 on 2025-11-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0015_policydatatest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PolicyDataTest',
        ),
    ]
