# Generated by Django 5.2.8 on 2025-11-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0016_delete_policydatatest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_Need',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
