# Generated by Django 5.2.8 on 2025-11-11 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0017_type_of_need'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type_of_Need',
            new_name='TypeOfNeed',
        ),
    ]
