# Generated by Django 5.2.8 on 2025-11-11 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0018_rename_type_of_need_typeofneed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_of_need',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_of_needs', to='Product_Management.typeofneed'),
            preserve_default=False,
        ),
    ]
