# Generated by Django 5.2.8 on 2025-11-12 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0020_policyownerpdffile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyownerpdffile',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_owner_pdf_file', to='Product_Management.product'),
        ),
    ]
