# Generated by Django 5.2.8 on 2025-11-12 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0023_product_user_productinfoimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product_Management.product'),
            preserve_default=False,
        ),
    ]
