# Generated by Django 5.2.8 on 2025-11-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0025_alter_productinfo_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyowner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='policyownerdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='policyownerpdffile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productinfoimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='typeofneed',
            name='user',
        ),
    ]
