# Generated by Django 5.2.8 on 2025-11-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0026_remove_policyowner_user_remove_policyownerdata_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='product_name',
            field=models.JSONField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='text1_extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='text2_extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='text3_extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='text4_extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
