# Generated by Django 5.2.8 on 2025-11-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0027_alter_productinfo_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
