# Generated by Django 5.2.8 on 2025-11-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Management', '0029_alter_productinfo_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfoimage',
            name='tags_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
