# Generated by Django 5.2.7 on 2025-10-28 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Owner_Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('style', models.CharField(max_length=100)),
                ('fields_names', models.CharField(max_length=255)),
                ('values', models.TextField()),
                ('policy_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.policy_owner')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('policy_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.policy_owner')),
            ],
        ),
    ]
