# Generated by Django 5.2.7 on 2025-10-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='policy_owner',
        ),
        migrations.DeleteModel(
            name='Policy_Owner_Content',
        ),
        migrations.DeleteModel(
            name='Policy_Owner',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
