# Generated by Django 5.2.7 on 2025-10-29 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0002_remove_product_policy_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy_Owner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('decription', models.TextField()),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Owner_Fields',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], max_length=50)),
                ('field_type_list', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='product_management.policy_owner')),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Owner_Values',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product_management.policy_owner_fields')),
                ('policy_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product_management.policy_owner')),
            ],
        ),
    ]
