# Generated by Django 5.2.7 on 2025-10-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_policy_owner_values_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy_owner_values',
            name='row',
            field=models.IntegerField(null=True),
        ),
    ]
