# Generated by Django 5.2.7 on 2025-10-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_alter_policy_owner_values_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy_owner_values',
            name='row',
        ),
    ]
