# Generated by Django 5.2.7 on 2025-10-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy_owner_values',
            name='row_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
