# Generated by Django 5.2.7 on 2025-10-30 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0009_policy_owner_values_row_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy_owner_fields',
            name='policy_owner',
        ),
        migrations.RemoveField(
            model_name='policy_owner_values',
            name='policy_owner',
        ),
        migrations.RemoveField(
            model_name='policy_owner_values',
            name='field',
        ),
        migrations.DeleteModel(
            name='Policy_Owner',
        ),
        migrations.DeleteModel(
            name='Policy_Owner_Fields',
        ),
        migrations.DeleteModel(
            name='Policy_Owner_Values',
        ),
    ]
